# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GFisSGSKjwvpV12XMH1UzUXjTWMhechd
"""

import numpy as np
import pandas as pd
from math import sqrt
import matplotlib.pyplot as plt

path="/content/drive/MyDrive/DATASET/train_updated.csv"
data=pd.read_csv(path)

x = np.array(data['x'])
y = np.array(data['y'])
m = x.size

n = y.size
m,n

x.shape

w = 0
b=0
itr = 10000
alpha = 0.000001
cost_history= []
w_history =[]
b_history = []

i = 0
while (i<=itr):
    yp = w*x+b
    cost = (1/(2*m))*np.sum(np.square(yp - y))
    djw = (1/m)*np.dot(x.T,yp-y)
    djb = (1/m)*(yp-y)
    w = w - alpha*djw
    b = b - alpha*djb
    cost_history.append(cost)
    w_history.append(w)
    b_history.append(b)
    i=i+1
    if(i%(itr//10) == 0):
      print("Cost is :", cost)

rng = np.arange(0, i)
plt.plot(rng, cost_history)
plt.show()

path="/content/drive/MyDrive/DATASET/test.csv"
test_dataset=pd.read_csv(path)

test_dataset

x_test=np.array(test_dataset['x'])
y_test=np.array(test_dataset['y'])
r=x_test.size
r

w_final = w_history[-1]
b_final = b_history[-1][-1]
ypf = w_final*x_test + b_final
sq = np.sum(np.square(y_test - ypf))
rt= sqrt(sq/r)
rt